version: '3'

services:

    lc_app:
        container_name: lc_app
        build: .
        command: flask run --port=5000 --host=0.0.0.0

        ports:
            - "5000:5000"
        volumes:
            - ./flaskr:/flaskr
        environment:
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - APP_PORT=5000
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dev
        depends_on:
            - lc_db
        networks:
            - lc_network

    lc_db:
        image: postgres
        container_name: "postgres_lc"
        environment:
            - POSTGRES_DB=db_local
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dev
            - TZ=GMT
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

        networks:
            - lc_network

networks:
  lc_network:
      driver: bridge
